name: cd

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
    - name: ソースコードのチェックアウト
      uses: actions/checkout@v4

    - name: OIDC 連携により AWS の認証情報を取得する
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ap-northeast-1
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

    - name: ECR に認証する
      uses: docker/login-actions@v3
      with:
        registry: ${{ secrets.AWS_ECR_URL }}

    - name: Docker ビルドおよびプッシュを実行する
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.AWS_ECR_URL }}/${{ secrets.IMAGE_NAME }}:latest

    - name: 新しいタスク定義を作る
      id: render-task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ secrets.CONTAINER_NAME}}
        image: &{{ secrets.AWS_ECR_URL }}/${{ secrets.IMAGE_NAME }}:latest

    - name: ECS にデプロイする
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.render-task-def.outputs.task-definition }}
        service: ${{ secrets.ECS_SERVICE_NAME }}
        cluster: ${{ secrets.ECS_CLOUSTER_NAME }}
        
